import Head from 'next/head';
import Image from 'next/image';
import About from '../components/about';
import Education from '../components/education';
import Experience from '../components/experience';
import Header from '../components/header';
import Nav from '../components/nav';
import Skills from '../components/skills/index';
import Portfolio from '../components/portfolio';
import Contact from '../components/contact';
import Footer from '../components/footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Desarrollador Javascript Full Stack - David&apos;s Devel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Header/>
      <About/>
      <Education/>
      <Skills/>
      <Experience/>
      <Portfolio/>
      <Contact/>
      <Footer/>
    </div>
  )
}
